### ISSUE TITLE
CloudWatch Monitoring

### ISSUE THREAD

**Issue by msjackiebrown** [msjackiebrown/java-aws-lambda-calculator#7]
Add CloudWatch metrics and logging:
```yaml
# Update template.yaml
Resources:
  CalculatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - CloudWatchLogsFullAccess
        - CloudWatchPutMetricPolicy
```
