### ISSUE TITLE
CORS Configuration Enhancement

### ISSUE THREAD

**Issue by msjackiebrown** [msjackiebrown/java-aws-lambda-calculator#8]
Update CORS configuration for better security:
```yaml
# Update template.yaml
FunctionUrlConfig:
  AuthType: NONE
  Cors:
    AllowOrigins:
      - "https://your-domain.com"
    AllowHeaders:
      - "content-type"
      - "x-api-key"
```
